# Generated by Django 2.2 on 2020-01-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
            ],
        ),
    ]
