# Generated by Django 2.2 on 2020-01-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0002_random'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='random',
            new_name='randoma',
        ),
    ]
