# Generated by Django 2.2 on 2020-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0003_auto_20200117_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='randoma',
        ),
        migrations.AddField(
            model_name='bottle',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
