# Generated by Django 2.2 on 2020-01-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0005_auto_20200118_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_nurse',
        ),
    ]
