# Generated by Django 2.2 on 2020-01-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0006_auto_20200118_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ward_id',
            field=models.IntegerField(null=True),
        ),
    ]
