# Generated by Django 2.2 on 2020-01-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0007_person_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
