# Generated by Django 2.2 on 2020-01-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0008_auto_20200118_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='threshold',
            field=models.IntegerField(null=True),
        ),
    ]
