# Generated by Django 2.2 on 2020-01-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0009_bottle_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='threshold',
            field=models.FloatField(null=True),
        ),
    ]
